config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'registrations'
  }
  resources :profiles do
    resources :skills
    resources :experiences
    resources :educations
  end
  
  resources :jobs

  get "/developers" => "developers#index"
  get "/designers" => "designers#index"

end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :profile
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :profile
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :student
	has_many :educations, dependent: :destroy
	has_many :experiences, dependent: :destroy
	has_many :projects, dependent: :destroy
	has_many :skills, dependent: :destroy
	has_attached_file :avatar, styles: {medium: "250x250>", thumb: "125x125>", default_url: "/images/missing.png"}
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	validates_uniqueness_of :student
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :profile
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy

  scope :sort_by_updated_profiles, -> { includes(:profile).order('profiles.updated_at DESC') }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
	def index
		@designers = Student.sort_by_updated_profiles.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
	def index
	@developers = Student.sort_by_updated_profiles.where(:job_type => "Developer").paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@developers = Student.where(:job_type => "Developer").paginate(:page => params[:page], :per_page => 3)
		@designers = Student.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 3)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		@jobs = Job.all.order("created_at DESC") 
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit 
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to jobs_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)
	end

	def find_job
		@job = Job.find(params[:id])
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def index
		@profiles = Profile.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@profile = Profile.new
	end

	def show
		@profile = Profile.find(params[:id]) 
	end

	def create
		@profile = Profile.new(profile_params)
		if @profile.save
			redirect_to profile_path(@profile.id)
		else
			flash[:alert] = "You already have a profile, please update original profile"
			redirect_to profile_path(current_student.profile.id)
		end
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])
		if @profile.update(profile_params)
			redirect_to show
		else
			flash[:alert] = "Please try again, please contact NYCDA if it continues"
			redirect_to show
		end
	end

	private
	def profile_params
		params.require(:profile).permit(:name, :status, :location, :student_id, :avatar)
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

	def create
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.create(skill_params)
		redirect_to profile_path(@profile.id)
	end

	def destroy
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.find(params[:id])
		@skill.destroy
		redirect_to profile_path(@profile.id)
	end

	private
	def skill_params
		params.require(:skill).permit(:profile_id, :name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/edits_helper.rb
module EditsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %> 
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description%> 
	</p>
	<p>
		<%= f.label :company %>
		<%= f.text_field :company %> 
	</p>
	<p>
		<%= f.label :link %>
		<%= f.text_field :url %> 
	</p>
	<p><%= f.submit %></p>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Job</h1>

<%= render "form" %>

<%= link_to "back", jobs_path %>

app/views/jobs/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-1">
			<% @jobs.each do |job| %>
				<h2><%= link_to job.title, job %></h2>
				<p><%= job.company %></p><hr>
			<% end %>
		</div>

		<div class="col-md-3">
			<h3><%= link_to "Post a Job", new_job_path %></h3>
		</div>
	</div>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render "form" %>

<%= link_to "back", jobs_path %>

app/views/jobs/show.html.erb
<h1><%= @job.title %></h1>
<p><%= @job.description %></p>
<p><%= @job.company %></p>
<p><%= @job.url %></p>

<%= link_to "back", jobs_path %>
<%= link_to "edit", edit_job_path %>
<%= link_to "delete", job_path(@job), method: :delete, data: { confirm: "are you sure?" } %>

app/views/profiles/edit.html.erb
<%= form_for @profile, method: :patch, html: { multipart: true } do |f| %>
  <%= f.file_field :avatar %>
	<%= f.text_field :name, placeholder:'Name' %>
	<%= f.text_area :status, placeholder:'Describe yourself in 1 or 2 sentences' %>
	<%= f.text_field :location, placeholder:'Where do you live?' %>
	<%= f.hidden_field :student_id, :value => current_student.id %>
	<%= f.submit 'Submit', id:'profile_submit' %>
<% end %>

app/views/profiles/index.html.erb
<!-- <div class="miniNav">
	<ul>
		<li><%= link_to "All Designers", designers_path %></li> 
		<li><%= link_to "All Developers", developers_path %></li>
	</ul>
</div> -->

<div class="gradPageHeader">
	<div class="container">
		<h1>Meet Our Graduates</h1>
	</div>
</div>


<div class="container">
	<div class="gradList row">
		<% @profiles.order("updated_at DESC").each do |p| %>
			<% if !p.experiences.last.nil? && !p.educations.last.nil? && !p.skills.nil? %>
				<!-- picture -->
				<div class="col-md-2 gradAvatar">
					<%= image_tag p.avatar.url(:thumb) %>
				</div>

				<div class="col-md-6">
				<!-- Name -->
					<h2><%= link_to p.name.titleize, profile_path(p.id) %></h2>
				<!-- Status -->
					<h4><em>Currently <%= p.status %> </em></h4>
				<!-- location -->
					<h5 class="location">
						<span class="glyphicon glyphicon-map-marker"></span> <%= p.location.titleize %>
					</h5><br>
				</div>
				<div class="row container">
					<!-- Experiences -->
					<div class="col-md-4">
						<p>
							<span class="glyphicon glyphicon-briefcase"></span>
							Previously a <b><%= p.experiences.last.title %></b>
							at <b><%= p.experiences.last.company %></b>
						</p>
					</div>
					<!-- Education -->
					<div class="col-md-4">
						<p>
							<span class="glyphicon glyphicon-education"></span>
							Degree in <b><%= p.educations.last.major %></b>
							at <b><%= p.educations.last.school %></b>
						</p>
					</div>
					<!-- Skills -->
					<div class="col-md-4">
						<p>
							<span class="glyphicon glyphicon-wrench"></span>
							<% p.skills.each do |s| %>
								{ <%= s.name %> }
							<% end %>
						</p>
					</div>
				</div>
			<% end %>
		<% end %>
		<hr>
	</div>
	<!-- paginate nav bar-->
	<div class="paginate_nav">
		<%= will_paginate @designers %>
	</div>	
</div>

app/views/profiles/new.html.erb
<%= form_for @profile, html: { multipart: true } do |f| %>
  <%= f.file_field :avatar %>
	<%= f.text_field :name, placeholder:'Name' %>
	<%= f.text_area :status, placeholder:'Describe your current status in 1 or 2 sentences' %>
	<%= f.text_field :location, placeholder:'Where do you live?' %>
	<%= f.hidden_field :student_id, :value => current_student.id %>
	<%= f.submit 'Submit', id:'profile_submit' %>
<% end %>

app/views/profiles/show.html.erb
<div class="candPageHeader">
	<div class="container">
		<div class="col-md-10 col-md-offset-1">
			<% if @profile.experiences.last.nil? %>
				<h3><em>I am <%= @profile.status %>. Read the rest of my journey below.</em></h3>
			<% else %>		
				<h3><em>"Before NYCDA, I was working as a <%= @profile.experiences.last.title %>, now I am <%= @profile.status %>. Read the rest of my journey below."</em></h3>
			<% end %>
		</div>
	</div>
</div>


<div class="container candProfile">
	<div class="row">
		<div class="candAvatar col-md-2 col-md-offset-1">
			<%= image_tag @profile.avatar.url(:thumb) %>
		</div>

		<% if student_signed_in? && @profile.student.id == current_student.id %>
			<%= link_to "Edit", edit_profile_path %>
			<%= render "skills/form" %>
			<%= render "skills/skills" %>
			<%= render "experiences/form" %>
			<%= render "experiences/experiences" %>
			<%= render "educations/form" %>
			<%= render "educations/educations" %>
		<% else %>
		<div class="candInfo col-md-8">
			<h1><%= @profile.name.titleize %></h1>
			<p>
				<span class="glyphicon glyphicon-map-marker"></span> <%= @profile.location.titleize %>
			</p><hr>

			<h3>Work Experience</h3><br>
			<ul>
				<% @profile.experiences.each do |e| %>
				<li>
					<h4><%= e.title.titleize %> at <%= e.company.titleize %></h4>
					<p>From <%= e.start %> to <%= e.end %></p>
					<p><%= e.description.capitalize %></p>
				</li><br>
				<% end %>
			</ul>

			<h3>Education</h3><br>
			<ul>
				<% @profile.educations.each do |e| %>
				<li>
					<h4><%= e.major.titleize %> at <%= e.school.titleize %></h4>
					<p><%= e.start %> to <%= e.graduate %></p>
				</li><br>
				<% end %>
			</ul>

			<h3>Skills</h3><br>
			<p>
				<% @profile.skills.each do |s| %>
					{ <%= s.name %> }
				<% end %>
			</p>
		</div>
	</div>
	<% end %>
</div>

<!-- 	<%= link_to "All Designers", designers_path %> <br>
	<%= link_to "All Developers", developers_path %> -->

app/views/skills/_form.html.erb
<h3>Add Skills: </h3>
<%= form_for([@profile, @profile.skills.build]) do |f| %>
	<p>
		<%= f.label :skills %>
		<%= f.text_field :name %> 
	</p>
	<%= f.hidden_field :profile_id, :value => @profile.id %>
	<p><%= f.submit %></p>
<% end %>

app/views/skills/_skills.html.erb
<h3>My Skills:</h3>
<ul>
	<!-- !element.id.nil? is same as element.id != nil -->
	<% @profile.skills.select{|element| !element.id.nil? }.each do |s| %>
		<li><%= s.name %>
			<%= link_to "X", [s.profile, s],
				method: :delete,
				data: { confirm: "Are you sure?" } %>
		</li>
	<% end %>
</ul>
<hr>