config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'registrations'
  }
  resources :profiles do
    resources :skills
    resources :experiences
    resources :educations
  end
  
  resources :jobs

  get "/developers" => "developers#index"
  get "/designers" => "designers#index"

end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :profile
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :profile
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :student
	has_many :educations, dependent: :destroy
	has_many :experiences, dependent: :destroy
	has_many :projects, dependent: :destroy
	has_many :skills, dependent: :destroy
	has_attached_file :avatar, styles: {medium: "250x250>", thumb: "125x125>", default_url: "/images/missing.png"}
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	validates_uniqueness_of :student
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :profile
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy

  scope :sort_by_updated_profiles, -> { includes(:profile).order('profiles.updated_at DESC') }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
	def index
		@designers = Student.sort_by_updated_profiles.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
	
	def create
		@profile = Profile.find(params[:profile_id])
		@experience = @profile.experiences.create(experience_params)
		redirect_to profile_path(@profile.id)
	end

	def edit
		@profile = Profile.find(params[:profile_id])
		@experience = @profile.experiences.find(params[:id])
		respond_to do |format|
			format.html { render "profiles/show.html"}
			format.js
		end
	end

	def update
		@profile = Profile.find(params[:profile_id])
		@experience = @profile.experiences.find(params[:id])
		@experience.update(experience_params)
		respond_to do |format|
			format.js
		end
	end

	def destroy
		@profile = Profile.find(params[:profile_id])
		@experience = @profile.experiences.find(params[:id])
		@experience.destroy
		redirect_to profile_path(@profile.id)
	end

	private
	def experience_params
		params.require(:experience).permit(:title, :company, :description, :start, :end, :profile_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@developers = Student.where(:job_type => "Developer").paginate(:page => params[:page], :per_page => 3)
		@designers = Student.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 3)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		@jobs = Job.all.order("created_at DESC") 
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit 
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to jobs_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)
	end

	def find_job
		@job = Job.find(params[:id])
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def index
		@profiles = Profile.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@profile = Profile.new
	end

	def show
		@profile = Profile.find(params[:id]) 
	end

	def create
		@profile = Profile.new(profile_params)
		if @profile.save
			redirect_to profile_path(@profile.id)
		else
			flash[:alert] = "You already have a profile, please update original profile"
			redirect_to profile_path(current_student.profile.id)
		end
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])
		if @profile.update(profile_params)
			redirect_to show
		else
			flash[:alert] = "Please try again, please contact NYCDA if it continues"
			redirect_to show
		end
	end

	private
	def profile_params
		params.require(:profile).permit(:name, :status, :location, :student_id, :avatar)
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

	def create
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.create(skill_params)
		redirect_to profile_path(@profile.id)
	end

	def destroy
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.find(params[:id])
		@skill.destroy
		redirect_to profile_path(@profile.id)
	end

	private
	def skill_params
		params.require(:skill).permit(:profile_id, :name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/edits_helper.rb
module EditsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/experiences/_experiences.html.erb
<h3>My Experiences:</h3>
<ul>
	<!-- !element.id.nil? is same as element.id != nil -->
	<!-- required select method for first user who does not have any posts yet -->
	<% @profile.experiences.select{|element| !element.id.nil? }.each do |e| %>
	<p>
		<li>Title: <%= e.title %></li>
		<li>Company: <%= e.company %></li>
		<li>Description: <%= e.description %></li>
		<li>Start Date: <%= e.start %></li>
		<li>End Date: <%= e.end %></li> 
			<%= link_to "delete", [e.profile, e],
				method: :delete,
				data: { confirm: "Are you sure?" } %>
			<%= link_to "edit", edit_profile_experience_path(@profile.id, e.id) %>
	</p>
	<% end %>
</ul>
<hr>

app/views/experiences/_form.html.erb
<h3>Add Experiences: </h3>
<%= form_for([@profile, @profile.experiences.build]) do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %> 
	</p>
	<p>
		<%= f.label :company %>
		<%= f.text_field :company %> 
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description%> 
	</p>
	<p>
		<%= f.label :start %>
		<%= f.date_select :start, 
			:order => [:day, :month, :year], 
			:prompt => {day: 'Choose day', month: 'Choose month', year: 'Choose year'},
			:start_year => 2000,
			:end_year => Date.today().year %> 
	</p>
	<p>
		<%= f.label :end %>
		<%= f.date_select :end, 
			:order => [:day, :month, :year], 
			:prompt => {day: 'Choose day', month: 'Choose month', year: 'Choose year'},
			:start_year => 2000,
			:end_year => Date.today().year %> 
	</p>
	<%= f.hidden_field :profile_id, :value => @profile.id %>
	<p><%= f.submit %></p>
<% end %>

app/views/experiences/edit.html.erb
<h3>Add Experiences: </h3>
<%= form_for([@experience.profile, @experience]) do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %> 
	</p>
	<p>
		<%= f.label :company %>
		<%= f.text_field :company %> 
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description%> 
	</p>
	<p>
		<%= f.label :start %>
		<%= f.date_select :start, 
			:order => [:day, :month, :year], 
			:prompt => {day: 'Choose day', month: 'Choose month', year: 'Choose year'},
			:start_year => 2000,
			:end_year => Date.today().year %> 
	</p>
	<p>
		<%= f.label :end %>
		<%= f.date_select :end, 
			:order => [:day, :month, :year], 
			:prompt => {day: 'Choose day', month: 'Choose month', year: 'Choose year'},
			:start_year => 2000,
			:end_year => Date.today().year %> 
	</p>
	<%= f.hidden_field :profile_id, :value => @profile.id %>
	<p><%= f.submit %></p>
<% end %>