config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'registrations'
  }
  resources :profiles do
    resources :skills
    resources :experiences
    resources :educations
  end
  
  resources :jobs

  get "/developers" => "developers#index"
  get "/designers" => "designers#index"

end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :profile
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :profile
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :student
	has_many :educations, dependent: :destroy
	has_many :experiences, dependent: :destroy
	has_many :projects, dependent: :destroy
	has_many :skills, dependent: :destroy
	has_attached_file :avatar, styles: {medium: "250x250>", thumb: "125x125>", default_url: "/images/missing.png"}
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	validates_uniqueness_of :student
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :profile
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy

  scope :sort_by_updated_profiles, -> { includes(:profile).order('profiles.updated_at DESC') }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
	def index
		@designers = Student.sort_by_updated_profiles.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 10)
	end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

	def create
		@profile = Profile.find(params[:profile_id])
		@education = Education.new(education_params)
		if @education.save
			redirect_to profile_path(@profile.id)
		else
			flash[:alert] = "error"
			redirect_to profile_path(@profile.id)
		end
	end

	def edit
		
	end

	def update
		@profile = Profile.find(params[:profile_id])
		
	end

	def destroy
		@profile = Profile.find(params[:profile_id])
		@education = @profile.educations.find(params[:id])
		@education.destroy
		redirect_to profile_path(@profile.id)
	end
	
	private
	def education_params
		params.require(:education).permit(:school, :major, :start, :graduate, :profile_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@developers = Student.where(:job_type => "Developer").paginate(:page => params[:page], :per_page => 3)
		@designers = Student.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 3)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		@jobs = Job.all.order("created_at DESC") 
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit 
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to jobs_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)
	end

	def find_job
		@job = Job.find(params[:id])
	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def index
		@profiles = Profile.all.paginate(:page => params[:page], :per_page => 10)
	end

	def new
		@profile = Profile.new
	end

	def show
		@profile = Profile.find(params[:id]) 
	end

	def create
		@profile = Profile.new(profile_params)
		if @profile.save
			redirect_to profile_path(@profile.id)
		else
			flash[:alert] = "You already have a profile, please update original profile"
			redirect_to profile_path(current_student.profile.id)
		end
	end

	def edit
		@profile = Profile.find(params[:id])
	end

	def update
		@profile = Profile.find(params[:id])
		if @profile.update(profile_params)
			redirect_to show
		else
			flash[:alert] = "Please try again, please contact NYCDA if it continues"
			redirect_to show
		end
	end

	private
	def profile_params
		params.require(:profile).permit(:name, :status, :location, :student_id, :avatar)
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

	def create
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.create(skill_params)
		redirect_to profile_path(@profile.id)
	end

	def destroy
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.find(params[:id])
		@skill.destroy
		redirect_to profile_path(@profile.id)
	end

	private
	def skill_params
		params.require(:skill).permit(:profile_id, :name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/edits_helper.rb
module EditsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/educations/_educations.html.erb
<h3>My Educations:</h3>
<!-- !element.id.nil? is same as element.id != nil -->
<% @profile.educations.select{|element| !element.id.nil? }.each do |edu| %>
	<p>
		School: <%= edu.school %> <br>
		Major: <%= edu.major %><br>
		Started: <%= edu.start %><br>
		Graduated: <%= edu.graduate %><br>
		<%= link_to "delete", [edu.profile, edu],
			method: :delete,
			data: { confirm: "Are you sure?" } %>
		<%= link_to "edit", edit_profile_education_path(@profile.id, edu.id) %>
	</p>
<% end %>
<hr>

app/views/educations/_form.html.erb
<h3>Add Education: </h3>
<%= form_for([@profile, @profile.educations.new]) do |f| %>
	<% if @profile.educations.new.errors.any? %>
		<h3>
			<%= pluralize(@profile.educations.new.errors.count, "error") %>
			Prohibited educations to be created
		</h3>
		<ul>
			<% @profile.educations.new.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :school %>
		<%= f.text_field :school %> 
	</p>
	<p>
		<%= f.label :major %>
		<%= f.text_field :major %> 
	</p>
	<p>
		<%= f.label :from %>
		<%= f.date_select :start, 
			:order => [:day, :month, :year], 
			:prompt => {day: 'Choose day', month: 'Choose month', year: 'Choose year'},
			:start_year => 2000,
			:end_year => Date.today().year %> 
	</p>
	<p>
		<%= f.label :grdauate %>
		<%= f.date_select :graduate, 
			:order => [:day, :month, :year], 
			:prompt => {day: 'Choose day', month: 'Choose month', year: 'Choose year'},
			:start_year => 2000,
			:end_year => Date.today().year %> 
	</p>
	<%= f.hidden_field :profile_id, :value => @profile.id %>
	<p><%= f.submit %></p>
<% end %>