config/routes.rb
Rails.application.routes.draw do

  root "home#index"

  devise_for :students, controllers: {
    sessions: 'students/sessions',
    registrations: 'registrations'
  }
  resources :profiles do
    resources :skills
    resources :experiences
    resources :educations
  end
  
  resources :jobs

  get "/developers" => "developers#index"
  get "/designers" => "designers#index"

end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :profile
end

app/models/experience.rb
class Experience < ActiveRecord::Base
	belongs_to :profile
end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :student
	has_many :educations, dependent: :destroy
	has_many :experiences, dependent: :destroy
	has_many :projects, dependent: :destroy
	has_many :skills, dependent: :destroy
	has_attached_file :avatar, styles: {medium: "250x250>", thumb: "125x125>", default_url: "/images/missing.png"}
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	validates_uniqueness_of :student
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :profile
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	belongs_to :profile
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile, dependent: :destroy

  scope :sort_by_updated_profiles, -> { includes(:profile).order('profiles.updated_at DESC') }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@developers = Student.where(:job_type => "Developer").paginate(:page => params[:page], :per_page => 3)
		@designers = Student.where(:job_type => "Designer").paginate(:page => params[:page], :per_page => 3)
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]

	def index
		@jobs = Job.all.order("created_at DESC") 
	end

	def show
	end

	def new
		@job = Job.new
	end

	def create
		@job = Job.new(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end
	end

	def edit 
	end

	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end
	end

	def destroy
		@job.destroy
		redirect_to jobs_path
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url)
	end

	def find_job
		@job = Job.find(params[:id])
	end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

	def create
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.create(skill_params)
		redirect_to profile_path(@profile.id)
	end

	def destroy
		@profile = Profile.find(params[:profile_id])
		@skill = @profile.skills.find(params[:id])
		@skill.destroy
		redirect_to profile_path(@profile.id)
	end

	private
	def skill_params
		params.require(:skill).permit(:profile_id, :name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/edits_helper.rb
module EditsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Profiles</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= favicon_link_tag 'logo.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to " { Profiles } ", root_path, :class => "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><%= link_to "OUR GRADUATES", profiles_path %></li>
	        <% if student_signed_in? && !current_student.profile.nil? %>
	        <li><%= link_to "JOBS", jobs_path %></li>
	      </ul>

	      <ul class="nav navbar-nav navbar-right">
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_student.email %> <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	          	<li><%= link_to "MY PROFILE", profile_path(current_student.profile.id) %></li>
	            <li><%= link_to "SETTINGS", edit_student_registration_path %></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "SIGN OUT", destroy_student_session_path, :method => :delete %></li>
	            <% elsif student_signed_in? && current_student.profile.nil? %>
	            <li><%= link_to "CREATE PROFILE", new_profile_path %></li>
	            <li><%= link_to "SETTINGS", edit_student_registration_path %></li>
	            <li role="separator" class="divider"></li>
	            <li><%= link_to "SIGN OUT", destroy_student_session_path, :method => :delete %></li>
	          </ul>
	        </li>
	      </ul>
	      <% else %>
	      </ul>
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "LOGIN", student_session_path %></li>
			<!-- <li><%= link_to "SIGN UP", new_student_registration_path %></li> -->
	      </ul>
	      <% end %>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

<!-- 
	<%= content_tag :div, flash[:notice], class: "alert alert-success" if flash[:notice] %>
	<%= content_tag :div, flash[:alert], class: "alert alert-danger" if flash[:alert] %> -->


	<%= yield %>


</body>
</html>